user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /user

tvdb:
    resource: "@TVDBBundle/Controller/"
    type:     annotation
    prefix:   /kittyadmin/tvdb

admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /kittyadmin

serie:
    resource: "@SerieBundle/Controller/"
    type:     annotation
    prefix:   /serie

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /
    
# HWIOAuthBundle
hwi_oauth_security:
    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
    prefix: /connect

hwi_oauth_redirect:
    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
    prefix:   /connect

# We override this part of the routing
hwi_oauth_connect:
     resource: "@AppBundle/Resources/config/routing/connect.xml"
     prefix: /connect

facebook_login:
    pattern: /connect/check-facebook

google_login:
    pattern: /connect/check-google

twitter_login:
    pattern: /connect/check-twitter

# FOSUser

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

